;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        cua-paste
        dabbrev-expand
        end-of-visual-line
        keyboard-escape-quit
        transpose-words
        ))

(setq mc/cmds-to-run-once
      '(
        ))
