;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        LaTeX-babel-insert-hyphen
        LaTeX-insert-left-brace
        TeX-insert-backslash
        beginning-of-visual-line
        cua-paste
        dabbrev-expand
        end-of-visual-line
        ignore
        keyboard-escape-quit
        mouse-set-region
        transpose-words
        ))

(setq mc/cmds-to-run-once
      '(
        orgtbl-self-insert-command
        ))
